name: imsdk_client_core
description: The client core library of Zhiyou real-time communication cloud service.
version: 1.2.3
homepage: https://github.com/yangfanyu/imsdk_client_core

environment:
  sdk: '>=2.17.0 <3.0.0'


dependencies: 
  lpinyin: ^2.0.3
  shelf_easy: ^1.0.6

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
