name: imsdk_client_core
description: A starting point for Dart libraries or applications.
version: 1.0.0
homepage: https://github.com/yangfanyu/imsdk_client_core

environment:
  sdk: '>=2.15.1 <3.0.0'


dependencies: 
  shelf_easy: ^0.0.9

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
