name: imsdk_client_core
description: A libraries for imsdk_server.
version: 0.0.62
homepage: https://github.com/yangfanyu/imsdk_client_core

environment:
  sdk: '>=2.16.2 <3.0.0'


dependencies: 
  lpinyin: ^2.0.3
  shelf_easy: ^0.0.58

dev_dependencies:
  lints: ^1.0.1
  test: ^1.21.1
